version: '2.2'

services:
#  app:
#    build: './app/'
#    ports:
#      - '80:8888'
#    restart: 'always'
#    volumes:
#      - './app:/app'
#  db:
#    image: mysql:5.7
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 'xxxx'
#      MYSQL_DATABASE: 'xxxx'
#      MYSQL_USER: 'xxxx'
#      MYSQL_PASSWORD: 'xxxx'
#  mongodb:
#    image: registry.withtopic.com:5000/wiztopic/mongodb:3.4.9
#    ports:
#      - "27017:27017"
#    volumes:
#      - /data/mongodb:/data/db
#      - /data/mongodump:/data/mongodump
#    command: mongod --smallfiles --storageEngine wiredTiger
#  nginx_php_fpm:
#    image: registry.withtopic.com:5000/wiztopic/nginx_php_fpm:7.1.23
#    ports:
#      - "80:8080"
#    volumes:
#      - <path2folder>:/var/www/dev/www
#    #  - /dev/shm/symfony/cache:/var/www/dev/www/app/cache
#    extra_hosts:
#      - "turbodash.local www.turbodash.local:192.168.33.9"
#    #shm_size: 1G
#  back:
#    image: python:3.7
#    depends_on:
#      - db
#    ports:
#      - 8080:8080
#    volumes:
#      - <path_to_api>:/opt/turbodash
#    working_dir: /opt/turbodash
